SCRUM-3315: create a new list of evidence codes
alliance-genome/agr_java_software pull request #1147
Opened 2024-01-05 15:10 UTC by abecerra

2024-01-05 16:09 UTC, oblodgett approved these changes

2024-01-05 16:12 UTC, oblodgett requested changes
This is still not right.

2024-01-05 16:14 UTC, oblodgett commented on agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/curation/DiseaseAnnotationCurationIndexer.java
> +
So the current list that is in the `GeneDiseaseAnnotationDocument gdad` needs to be added to, not overridden. So you need to take the list that is in gdad and add those to the map first then add the ones from da and do the setEvidenceCodes.

2024-01-05 16:23 UTC, abecerra commented on agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/curation/DiseaseAnnotationCurationIndexer.java
> +
ok

2024-01-08 02:31 UTC, oblodgett approved these changes

2024-01-08 09:45 UTC, merged