SCRUM-4092 make all disease qualifier names be their original names i…
alliance-genome/agr_java_software pull request #1196
Opened 2024-05-28 15:00 UTC by cmpich

…ncluding underscores

2024-05-28 15:02 UTC, abecerra approved these changes

2024-05-28 15:10 UTC, oblodgett commented on agr_indexer/src/main/java/org/alliancegenome/indexer/indexers/curation/DiseaseAnnotationCurationIndexer.java
> +			throw new RuntimeException("CreateImplicatedDA() Disease Annotations can only be used for AGM DAs or Allele DAs.");
This runtime exception can be brought up to line 203.

2024-05-28 15:39 UTC, oblodgett requested changes
The if else should be brought up to the earlier if/else so that the instance checking all happens in one spot.

2024-05-29 15:51 UTC, oblodgett approved these changes

2024-05-29 16:00 UTC, merged